### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by mormerod** [danieldiekmeier/textexpander-to-alfred3#11]
Tried to run and get the following error:

te2a3 Mike.textexpander 
/usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:26
  const name = !snippet.label || snippet.label === '' ? snippet.abbreviation.slice(0, 10) : snippet.label
                                                                             ^

TypeError: Cannot read property 'slice' of undefined
    at transformSnippet (/usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:26:78)
    at Array.map (<anonymous>)
    at textexpander2Alfred (/usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:71:6)
    at /usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:55:21
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

**Comment by danieldiekmeier** [comment]
I converted all my snippets over 3 years ago and haven't used TextExpander since, so I can't really do too much to help here. Especially without an example file that reproduces the error. (This is just a general advice if you want to write good issues, it will not actually help in this case.)

I‘m not really interested in spending my own time to fix this, but I‘d look at a Pull Request if someone would create one.

**Comment by matthewmcvickar** [comment]
@mormerod This is fixed now!
