### ISSUE TITLE
Web converter down

### ISSUE THREAD

**Issue by adeloscope** [danieldiekmeier/textexpander-to-alfred3#14]
Thanks for this tool! Web converter says site can't be reached once upload is complete and Convert button is pushed. 

<img width="635" alt="Screen Shot 2019-11-23 at 10 00 45 PM" src="https://user-images.githubusercontent.com/2516022/69490442-de61cf00-0e3c-11ea-8730-06e12edb019c.png">

**Comment by danieldiekmeier** [comment]
Hey @adeloscope, thanks for the heads up. The converter is probably not down, it just errors without showing a real error page. I just fixed that, but it will not fix your problem.

The problem is that I programmed this in April 2016. I then converted all my snippets, so I haven't needed this tool since. In the last years, both TextExpander and Alfred have released several new versions, which may or may not work with this tool (Judging by the support requests I get, they don't!)

If the website does not work, I can't help you. If you know Node.js, you may be able to fix it yourself and send a Pull Request to my respository. I will probably accept it!
